### ISSUE TITLE
非常喜欢这款主题

### ISSUE THREAD

**Issue by Mackel123** [IsoaSFlus/kcm-colorful#1]
非常喜欢这款主题，看起来也相当漂亮，不过有时候并不能根据图片改变主题颜色

**Comment by THMonster** [comment]
确实有一些bug，不过能不能麻烦描述一下具体状况？

**Comment by Rasphino** [comment]
我今天发现了一个问题
使用这张图片时会crash：https://mspoweruser.com/wp-content/uploads/2018/11/windowslight.jpg

**Comment by THMonster** [comment]
@Rasphino 对的，这个就是已知bug，虽然我也不太清楚为什么这张图片会crash2333

**Comment by Mackel123** [comment]
> @Rasphino 对的，这个就是已知bug，虽然我也不太清楚为什么这张图片会crash2333

![image](https://user-images.githubusercontent.com/27003282/50381862-95554800-06cc-11e9-97f0-514edd7ba5bf.png)
使用过程中发现kcmcolorhelper -s只会在黑色白色之间进行选择～
另外kcmcolorful --p现在在路径中的任何图片都是crash～

**Comment by THMonster** [comment]
> > @Rasphino 对的，这个就是已知bug，虽然我也不太清楚为什么这张图片会crash2333
> 
> ![image](https://user-images.githubusercontent.com/27003282/50381862-95554800-06cc-11e9-97f0-514edd7ba5bf.png)
> 使用过程中发现kcmcolorhelper -s只会在黑色白色之间进行选择～
> 另外kcmcolorful --p现在在路径中的任何图片都是crash～

你这个用错了。。。-s要和-p选项一起使用。。。。-s的意思是把-p指定的图片设置为壁纸。。。

**Comment by Mackel123** [comment]
> > > @Rasphino 对的，这个就是已知bug，虽然我也不太清楚为什么这张图片会crash2333
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/27003282/50381862-95554800-06cc-11e9-97f0-514edd7ba5bf.png)
> > 使用过程中发现kcmcolorhelper -s只会在黑色白色之间进行选择～
> > 另外kcmcolorful --p现在在路径中的任何图片都是crash～
> 
> 你这个用错了。。。-s要和-p选项一起使用。。。。-s的意思是把-p指定的图片设置为壁纸。。。

意思是kcmcolorful -s -p XXX.jpg吗？

**Comment by THMonster** [comment]
@Mackel123 对
