### ISSUE TITLE
Build....

### ISSUE THREAD

**Issue by j3st3r-LulzSec** [IsoaSFlus/kcm-colorful#11]
i have all dependencies and keep getting this build error:
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5QuickControls2"
  with any of the following names:

    Qt5QuickControls2Config.cmake
    qt5quickcontrols2-config.cmake

  Add the installation prefix of "Qt5QuickControls2" to CMAKE_PREFIX_PATH or
  set "Qt5QuickControls2_DIR" to a directory containing one of the above
  files.  If "Qt5QuickControls2" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:19 (find_package)
-- Configuring incomplete, errors occurred!

**Comment by THMonster** [comment]
Lost some dependencies, please check again.
