### ISSUE TITLE
Couldn't detect my wallpaper

### ISSUE THREAD

**Issue by Mackel123** [IsoaSFlus/kcm-colorful#12]
When I have installed the program, the colorful has showed on the setting but it couldn't detect my wallpaper.

**Comment by THMonster** [comment]
What wallpaper plugin are you using?
Kcm-colorful can only detect wallpaper correctly under the default wallpaper plugin.

**Comment by Mackel123** [comment]
[不好意思，之前中文输入法没有装成功，我用的插件还是kde自带的image插件，但还是无法识别](url)

系统信息：
Operating System: openSUSE Tumbleweed 20200128
KDE Plasma Version: 5.17.5
KDE Frameworks Version: 5.66.0
![_yande re 559431 ibara_dance seifuku wallpaper](https://user-images.githubusercontent.com/27003282/73640062-9666f000-46a8-11ea-8c0a-3dfbc92fcb05.jpg)

Qt Version: 5.14.0
Kernel Version: 5.4.14-1-default
OS Type: 64-bit
Processors: 6 × Intel® Core™ i5-9400F CPU @ 2.90GHz
Memory: 7.7 GiB of RAM

**Comment by THMonster** [comment]
你是否使用了kde的activity？多activity的话，也是无法识别的。

**Comment by Mackel123** [comment]
只用了一个activity

**Comment by THMonster** [comment]
能否多提供一些相关信息，截图之类的。

**Comment by Mackel123** [comment]
![Screenshot_20200203_220005](https://user-images.githubusercontent.com/27003282/73659157-9bd83080-46d0-11ea-9d7f-0dd6a8a7bf09.png)

**Comment by Mackel123** [comment]
![Screenshot_20200203_220113](https://user-images.githubusercontent.com/27003282/73659206-b90cff00-46d0-11ea-86de-8579d1329a40.png)

**Comment by THMonster** [comment]
重新设置成其他壁纸也没有用吗？

**Comment by Mackel123** [comment]
对

**Comment by THMonster** [comment]
请在终端运行：
```
 qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "var d = desktops();\
                        d[0].currentConfigGroup = Array(\"Wallpaper\", \"org.kde.image\", \"General\");\
                        a = d[0].readConfig(\"Image\");a.a()"
```


然后把输出贴上来看看

**Comment by Mackel123** [comment]
`The program 'qdbus' can be found in the following package:  
  * libqt4 [ path: /usr/bin/qdbus, repository: zypp (packman) ]  

    Try installing with  
       sudo zypper install libqt4`

已解决，感谢，原因是缺少libqt4软件包

**Comment by THMonster** [comment]
查了下发现qdbus这东西还真不是qt5默认就带了的，看来我得把这东西给换了。
谢谢你的反馈。

**Comment by Mackel123** [comment]
没事哈哈～因为很久之前就像反馈啦～，可以close bug problem了～
