### ISSUE TITLE
一个通知栏图标的 bug

### ISSUE THREAD

**Issue by eatradish** [IsoaSFlus/kcm-colorful#2]
复现步骤：

1. 从 breeze 主题切换到 colorful 主题，通知烂的更多图标按钮下会有一些白边残留，如图：
https://img.vim-cn.com/e5/57a06157102f17f04ec1285765450211231a52.jpg 
2. 重启后就完全变成了这个样子：
https://img.vim-cn.com/5a/94b276ef15d9b17870c55955d4371f4fee637c.jpg 
以下是正常的图：（breeze 主题）
https://img.vim-cn.com/ff/792fe21bf0cc2e4fe380ce96e4864828d219f8.jpg 

复现环境与设备：
1. AOSC OS KDE 5.15.0 and 1366*768 显示屏
2. Arch Linux KDE 5.15.0 and 1200*800 显示屏

**Comment by THMonster** [comment]
抱歉，你这三张图我看了半天没明白你指的是什么，能不能编辑一下图片指个箭头什么的QAQ

**Comment by THMonster** [comment]
明白什么问题了，我尝试修复一下。
