### ISSUE TITLE
我又来反馈问题啦～

### ISSUE THREAD

**Issue by Mackel123** [IsoaSFlus/kcm-colorful#5]
-- Install configuration: ""
-- Installing: /usr/share/color-schemes/ColorfulDark.colors
-- Installing: /usr/share/color-schemes/ColorfulLight.colors
CMake Error at cmake_install.cmake:48 (file):
  file INSTALL cannot find
  "/home/mackel2019/Documents/kcm-colorful/plasmathemes/kde-theme-backup/Colorful".

make: *** [Makefile:129：install] 错误 1

**Comment by THMonster** [comment]
你没拉submodule, 请google git submodule

**Comment by THMonster** [comment]
建议如 https://github.com/IsoaSFlus/kcm-colorful#build 中所写的，在clone的时候加上--recursive来得方便。
另外，如果你在使用archlinux，推荐直接用cn源里面的包。
