### ISSUE TITLE
无论怎么修改颜色，状态栏始终只匹配默认的黑色

### ISSUE THREAD

**Issue by eatradish** [IsoaSFlus/kcm-colorful#6]
KDE + manjaro stable，最新的 git 版本

**Comment by eatradish** [comment]
窗口标题懒颜色正常

**Comment by THMonster** [comment]
请贴出截图

**Comment by eatradish** [comment]
> 请贴出截图

https://img.vim-cn.com/0b/2f41f284e3038e88fa6debd76e5c491e93fd9a.png

**Comment by THMonster** [comment]
> > 请贴出截图
> 
> https://img.vim-cn.com/0b/2f41f284e3038e88fa6debd76e5c491e93fd9a.png

你的desktop theme设置成Colorful了吗

**Comment by eatradish** [comment]
> > > 请贴出截图
> > 
> > 
> > https://img.vim-cn.com/0b/2f41f284e3038e88fa6debd76e5c491e93fd9a.png
> 
> 你的desktop theme设置成Colorful了吗

已经设置了

**Comment by THMonster** [comment]
> > > > 请贴出截图
> > > 
> > > 
> > > https://img.vim-cn.com/0b/2f41f284e3038e88fa6debd76e5c491e93fd9a.png
> > 
> > 
> > 你的desktop theme设置成Colorful了吗
> 
> 已经设置了

重启试过吗？

**Comment by eatradish** [comment]
> > > > > 请贴出截图
> > > > 
> > > > 
> > > > https://img.vim-cn.com/0b/2f41f284e3038e88fa6debd76e5c491e93fd9a.png
> > > 
> > > 
> > > 你的desktop theme设置成Colorful了吗
> > 
> > 
> > 已经设置了
> 
> 重启试过吗？

试过了

**Comment by eatradish** [comment]
第二次重启后又正常了...奇了怪
