### ISSUE TITLE
panel 和 latte-dock 的颜色需注销才生效

### ISSUE THREAD

**Issue by magicshield** [IsoaSFlus/kcm-colorful#8]
plasma 主题是 colorful，窗口装饰是 breeze-blurred。
当用应用过颜色后，再更换颜色只有窗口装饰颜色更改，panel 和 latte-dock 以及它们的 tooltip 等的颜色都还是旧的，只有注销再登入才会使用新的颜色。
![panel 和 titlebar 颜色不同](https://user-images.githubusercontent.com/5268490/58060379-c797a280-7ba3-11e9-9946-b2a893ebfd12.png)

**Comment by THMonster** [comment]
这类问题基本都是kde自身的问题，因为我所做的只是发个dbus signal让kde自身知道color scheme发生了改变。
然后我想问下你是不是5.16 beta的kde？因为我现在用的就是5.16 beta，和你一模一样的问题。
另外你也可以试试kde的颜色设置里面应用新color scheme是否工作正常。
再另外，重启kde不必注销，kde可以像gnome一样不注销重启自身。参考：
```
#!/bin/bash
plasmashell --replace &
kwin_x11 --replace &
pkill krunner
krunner &
sleep 1
latte-dock --replace &
```
其中krunner 和 latte-dock是否要重启看个人需求。同时建议在krunner中运行，比较方便。

**Comment by magicshield** [comment]
5.15.5。
我试了试，kwin_x11 --replace 就可以改变 panel 和 tooltips 了。plasmashell --replace 倒是无效。

**Comment by THMonster** [comment]
今天发现kde 5.16好像修了这个问题，不过又引入了一个老问题（我真不清楚这是feature还是bug了），不过我暂且是解决了这个问题，您可以试试看是否工作正常。

**Comment by magicshield** [comment]
好了，正常工作了。
